[package]
name = "pico-8-palette-pal"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
rgb   = "0.8"
oklab = "1.1"

# Improved panic messages in browser console.
console_error_panic_hook = "0.1"
